### ISSUE TITLE
No turbosoap branch in GAP

### ISSUE THREAD

**Issue by tiandijunhao** [mcaroba/turbogap#1]
Dear sir,
When I use the commond "git clone -b turbosoap https://github.com/libAtoms/GAP.git" , an error occurred.
```
$ git clone -b turbosoap https://github.com/libAtoms/GAP.git
Cloning into 'GAP'...
fatal: Remote branch turbosoap not found in upstream origin

```
Is there a new command to download it？

Best regards,
Hao Wang

**Comment by mcaroba** [comment]
Hi Hao,

We're in the process of merging the GAP and GAP_turbo libraries and some things are not working as they should. There is no `turbosoap` branch of the GAP repo anymore. The way to get soap_turbo descriptors in QUIP is to first install TurboGAP after cloning recursively:

    git clone --recursive http://github.com/mcaroba/turbogap.git
    cd turbogap; make
    cd ..
    git clone --recursive http://github.com/libatoms/quip.git
    cd quip
    export QUIP_ARCH="linux_x86_64_gfortran"
    make config # make sure you build with GAP and pass the TurboGAP root directory
    make

Obviously you'll need to change things like installation directories and compiler options if you don't want the ones selected above.

There was a bug in QUIP's `Makefile.config` that I just fixed, so make sure you clone the latest development version of QUIP.
