### ISSUE TITLE
Different results when running the process on 2 CPU cores and 4 CPU cores

### ISSUE THREAD

**Issue by abd-adhyatma** [mcaroba/turbogap#5]
Greetings! I've been trying to use the TurboGAP code to do molecular dynamics fueled by the GAP provided in this [repository](https://doi.org/10.5281/zenodo.4616342) and related paper. I'm running a melting process on a supercomputer, and the code seems to produce different results depending on the number of cores used. The related files can be found [here](https://github.com/abd-adhyatma/turbogap-mpirun-issue.git).<Br>
The issue seems to stem from the process producing `0` or `NaN` for forces in the first step. When trying to use more cores, the issue is consistently reproduced. Any and all help with troubleshooting this issue would be greatly appreciated!

**Comment by abd-adhyatma** [comment]
Hi, TurboGAP team. Something strange has happened. I reinstalled TurboGAP with the intention of enabling debug flags in the makefile. For some reason, when I used this installation, the error seemed to stop occurring! I compared it by running the calculation using 16 cores with an installation that has the debug flags disabled, and you can find the results [here](https://github.com/abd-adhyatma/turbogap-mpirun-issue.git). 

It's curious. Do you perhaps have a plausible explanation as to what is causing this, and whether or not the errors have completely been removed?

Furthermore, I have just noticed some issues when running the above calculation with 16 cores that the output in the terminal by TurboGAP says that it finished in ~250 seconds, but in real time it takes considerably longer. Would you also have some insight about this?

Thank you for your attention. Feel free to respond whenever convenient.

**Comment by mcaroba** [comment]
My prime suspect would be some incompatibility between the compiler suite used to build TurboGAP and those used to run it. Or perhaps a similar incompatibility with the compiler suite used to build the LAPACK/BLAS libraries.

You can check if doing `export OMP_NUM_THREADS=1` before running the calculation leads to more reliable timings.

**Comment by abd-adhyatma** [comment]
I see. I would definitely look deeper into it if possible. Thank you, Dr. Caro.
